### ISSUE TITLE
非阿里云机器不能安装的吗？

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [alibaba/iot_remote_access#1]
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o RemoteTerminalDaemon_static -Wl,-rpath=/home/wanke/Desktop/services/iot_remote_access-master/board/centos/lib/ src/core/config_manager.o src/core/net_protocol.o src/core/remote_terminal.o src/core/session_mgr.o src/utility/hash_table/hash_table.o src/utility/json/json_parser.o src/utility/log/simple_log.o src/utility/misc/misc.o src/utility/sha256/hmac-sha256.o src/utility/sha256/main.o src/utility/sha256/sha256.o src/connectivity/rd_net.o src/connectivity/ws_nopoll.o board/centos/lib/libnopoll.a board/centos/lib/libssl.a board/centos/lib/libcrypto.a -Lboard/centos/lib -lpthread -ldl
/usr/bin/ld: board/centos/lib/libnopoll.a(nopoll.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: board/centos/lib/libnopoll.a(nopoll_ctx.o): relocation R_X86_64_32 against symbol `__nopoll_ctx_sigpipe_do_nothing' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: board/centos/lib/libnopoll.a(nopoll_conn.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: board/centos/lib/libnopoll.a(nopoll_log.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: board/centos/lib/libnopoll.a(nopoll_listener.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: board/centos/lib/libnopoll.a(nopoll_loop.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: board/centos/lib/libnopoll.a(nopoll_io.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
scons: *** [RemoteTerminalDaemon_static] Error 1
scons: building terminated because of errors.
unbuntu 18失败

**Comment by xiaowenhuyuehu** [comment]
您好，我们这个软件是不限制宿主机，只要是Linux/MacOS/Windows/Android/Arm Linux等都是可以支持的。

如果是X86 64位的主机，可以使用WIKI里的一键安装脚本，快速体验:
https://github.com/alibaba/iot_remote_access/wiki#%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85

如果是嵌入式(Arm/MIPS)的设备，需要自行进行交叉编译:
https://github.com/alibaba/iot_remote_access#%E7%BC%96%E8%AF%91%E5%85%B6%E4%BB%96%E5%B9%B3%E5%8F%B0

如果需要在X86平台上源码编译，需要参考交叉编译的文档，手动编译openssl/nopoll这两个第三方库，创建board目录后，scons编译:
https://github.com/alibaba/iot_remote_access/blob/master/docs/howto-cross-compile.md
