### ISSUE TITLE
可以支持一型一密吗？

### ISSUE THREAD

**Issue by LeeSSXX** [alibaba/iot_remote_access#2]
有时候机器运行于一型密的状态下，不可能每台都指定三要素，不知道这个功能，什么时候可以加上，另外为什么静态编译取消了，能不能编译出来少一些依赖的bin文件

**Comment by xiaowenhuyuehu** [comment]
> 有时候机器运行于一型密的状态下，不可能每台都指定三要素，不知道这个功能，什么时候可以加上，另外为什么静态编译取消了，能不能编译出来少一些依赖的bin文件

------------
1. 为了尽可能与LinkKit解耦，当前开源版本是不提供基于一型一密方式来实现云端建连的。建议一型一密场景下，通过调用LinkKit SDK获取设备/网关三元组后，再启动本服务。

2. 有些客户反馈静态编译的binary size过大，故取消了默认的静态编译方式。开发者可以自行修改Makefile来选择是否静态链接依赖的库。

**Comment by LeeSSXX** [comment]
谢谢，有时候确实需要静态编译的，最好还是支持静态和动态，两个选择，谁想用哪个用哪个，你觉得呢

**Comment by xiaowenhuyuehu** [comment]
> 谢谢，有时候确实需要静态编译的，最好还是支持静态和动态，两个选择，谁想用哪个用哪个，你觉得呢

可以，下个版本加回来。

**Comment by tanyjin123** [comment]
> 谢谢，有时候确实需要静态编译的，最好还是支持静态和动态，两个选择，谁想用哪个用哪个，你觉得呢

已经支持静态编译。README中有操作说明，记得查看。。。
