### ISSUE TITLE
Windows 上如何设置开机启动？

### ISSUE THREAD

**Issue by CongAn** [alibaba/iot_remote_access#5]
尝试了“任务计划程序”，能够自动启动程序，但是远程助手并不会显示在线状态。
在后台程序中存在“RemoteAccessDaemon.exe”，不知道具体运行状态。

**Comment by CongAn** [comment]
是按照此教程安装的：https://www.yuque.com/yuehu/link_iot_edge_lite/qbsh53

**Comment by tanyjin123** [comment]
> 尝试了“任务计划程序”，能够自动启动程序，但是远程助手并不会显示在线状态。
> 在后台程序中存在“RemoteAccessDaemon.exe”，不知道具体运行状态。

windows 版本不支持”设备上线“通知机制；
